name: Push to Replicate

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Cog
        run: |
          sudo curl -o /usr/local/bin/cog -L "https://github.com/replicate/cog/releases/latest/download/cog_$(uname -s)_$(uname -m)"
          sudo chmod +x /usr/local/bin/cog

      - name: Login to Replicate
        run: cog login --token "${{ secrets.COG_CLI_TOKEN }}"

      - name: Push to Replicate
        run: cog push r8.im/shiyi-12138/anytext
